language: android
before_install:
 - chmod +x ./gradlew
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
deploy:
  provider: releases
  api_key: $OUATH_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    tags: true
script:
- "./gradlew clean build --stacktrace"
